# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1314, 908)
        MainWindow.setStyleSheet("QWidget {\n"
"  background-color: #19232D;\n"
"  border: 0px solid #455364;\n"
"  padding: 0px;\n"
"  color: #E0E1E3;\n"
"  selection-background-color: #346792;\n"
"  selection-color: #E0E1E3;\n"
"    font-family : Ubuntu;\n"
"font-size: 18px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QWidget:disabled {\n"
"  background-color: #19232D;\n"
"  color: #9DA9B5;\n"
"  selection-background-color: #26486B;\n"
"  selection-color: #9DA9B5;\n"
"}\n"
"\n"
"QWidget::item:selected {\n"
"  background-color: #176B87;\n"
"}\n"
"\n"
"QWidget::item:hover:!selected {\n"
"  background-color: rgba(23, 107, 135,50%);\n"
"}\n"
"\n"
"QMainWindow::separator {\n"
"  background-color: #455364;\n"
"  border: 0px solid #19232D;\n"
"  spacing: 0px;\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QMainWindow::separator:hover {\n"
"  background-color: #60798B;\n"
"  border: 0px solid #1A72BB;\n"
"}\n"
"\n"
"/*-------------------------------------------------------------------------------------------*/\n"
"\n"
"QCheckBox {\n"
"  background-color: #FAFAFA;\n"
"  color: #19232D;\n"
"  spacing: 4px;\n"
"  outline: none;\n"
"  padding-top: 4px;\n"
"  padding-bottom: 4px;\n"
"}\n"
"\n"
"\n"
"\n"
"QCheckBox QWidget:disabled {\n"
"  background-color: #FAFAFA;\n"
"  color: #788D9C;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"  margin-left: 2px;\n"
"  height: 14px;\n"
"  width: 14px;\n"
"}\n"
"\n"
"/*-------------------------------------------------------------------------------------------*/\n"
"QScrollBar:horizontal {\n"
"  height: 16px;\n"
"  margin: 2px 16px 2px 16px;\n"
"  border: 1px solid white;\n"
"  border-radius: 4px;\n"
"  background-color: rgb(25, 35, 45);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"  background-color: #176B87;\n"
"  border: 1px solid #C9CDD0;\n"
"  border-radius: 4px;\n"
"  min-width: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"  background-color: rgba(23, 107, 135,80%);\n"
"  border:#4169E1;\n"
"  border-radius: 4px;\n"
"  min-width: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:focus {\n"
"  border: 1px solid red;\n"
"}\n"
"QScrollBar:vertical {\n"
"  background-color: rgb(25, 35, 45);\n"
"  width: 16px;\n"
"  margin: 16px 2px 16px 2px;\n"
"  border: 1px solid white;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical {\n"
"  background-color: #176B87;\n"
"  border: 1px solid #C9CDD0;\n"
"  min-height: 8px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"  background-color: rgba(23, 107, 135,80%);\n"
"  border: #9FCBFF;\n"
"  border-radius: 4px;\n"
"  min-height: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:focus {\n"
"  border: 1px solid #73C7FF;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"  margin: 0px 0px 0px 0px;\n"
"  border-image: url(\"qss_icons/light/rc/arrow_right_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: right;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover, QScrollBar::add-line:horizontal:on {\n"
"  border-image: url(\"qss_icons/light/rc/arrow_right.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: right;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"  margin: 3px 0px 3px 0px;\n"
"  border-image: url(\"qss_icons/light/rc/arrow_down_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: bottom;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on {\n"
"  border-image: url(\"qss_icons/light/rc/arrow_down.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: bottom;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"  margin: 0px 3px 0px 3px;\n"
"  border-image: url(\"qss_icons/light/rc/arrow_left_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: left;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:hover, QScrollBar::sub-line:horizontal:on {\n"
"  border-image: url(\"qss_icons/light/rc/arrow_left.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: left;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"  margin: 3px 0px 3px 0px;\n"
"  border-image: url(\"qss_icons/light/rc/arrow_up_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover, QScrollBar::sub-line:vertical:on {\n"
"  border-image: url(\"qss_icons/light/rc/arrow_up.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"  background: none;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"  background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"  background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"  background: none;\n"
"}\n"
"\n"
"/*----------------------------------------------------------------------------------------*/\n"
"QPushButton{\n"
" /*border:2px solid #05B8CC;*/\n"
" background-color: #176B87;\n"
" color:rgb(255, 255, 255);\n"
" border-radius: 10px;\n"
" font-weight:bold;\n"
"  transition: 500ms;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
" border: 1px solid #176B87;\n"
" background-color: rgba(23, 107, 135,80%)\n"
"}\n"
"QPushButton:pressed {\n"
" margin:1px 2px;\n"
" font-size: 15px;\n"
"}\n"
"/*----------------------------------------------------------------------------------------*/\n"
"QComboBox{\n"
" border:1px solid #176B87;\n"
"border-radius:5px;\n"
"background-color: #176B87;\n"
"padding: 2px 10px;\n"
"color:white;\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(icons/caret-down copy.svg);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"border:none;\n"
"    selection-background-color:#176B87;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_5.setContentsMargins(16, 11, 16, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.open_btn = QtWidgets.QPushButton(self.header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_btn.sizePolicy().hasHeightForWidth())
        self.open_btn.setSizePolicy(sizePolicy)
        self.open_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.open_btn.setMaximumSize(QtCore.QSize(100, 35))
        self.open_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_btn.setStyleSheet("")
        self.open_btn.setObjectName("open_btn")
        self.horizontalLayout_5.addWidget(self.open_btn)
        self.mode_comboBox = QtWidgets.QComboBox(self.header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mode_comboBox.sizePolicy().hasHeightForWidth())
        self.mode_comboBox.setSizePolicy(sizePolicy)
        self.mode_comboBox.setMaximumSize(QtCore.QSize(180, 35))
        self.mode_comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mode_comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.mode_comboBox.setObjectName("mode_comboBox")
        self.mode_comboBox.addItem("")
        self.mode_comboBox.addItem("")
        self.mode_comboBox.addItem("")
        self.mode_comboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.mode_comboBox)
        spacerItem = QtWidgets.QSpacerItem(508, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 4)
        self.verticalLayout.addWidget(self.header_frame)
        self.time_graph_frame = QtWidgets.QFrame(self.centralwidget)
        self.time_graph_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.time_graph_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.time_graph_frame.setObjectName("time_graph_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.time_graph_frame)
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        # self.original_graphics_view = QtWidgets.QGraphicsView(self.time_graph_frame)
        self.original_graphics_view = pg.PlotWidget(self.time_graph_frame)
        self.original_graphics_view.setMouseEnabled(x=True, y=True) 
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.original_graphics_view.sizePolicy().hasHeightForWidth())
        self.original_graphics_view.setSizePolicy(sizePolicy)
        self.original_graphics_view.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.original_graphics_view.setMouseTracking(True)
        self.original_graphics_view.setTabletTracking(True)
        self.original_graphics_view.setAcceptDrops(True)
        # self.original_graphics_view.setAutoFillBackground(False)
        self.original_graphics_view.setBackground('#19232D')
        self.original_graphics_view.setStyleSheet("")
        self.original_graphics_view.setObjectName("original_graphics_view")
        self.horizontalLayout.addWidget(self.original_graphics_view)
        self.original_sound_btn = QtWidgets.QPushButton(self.time_graph_frame)
        self.original_sound_btn.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border:none;")
        self.original_sound_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/volume.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.original_sound_btn.setIcon(icon)
        self.original_sound_btn.setIconSize(QtCore.QSize(25, 25))
        self.original_sound_btn.setObjectName("original_sound_btn")
        self.horizontalLayout.addWidget(self.original_sound_btn)
        # self.equalized_graphics_view = QtWidgets.QGraphicsView(self.time_graph_frame)
        self.equalized_graphics_view = pg.PlotWidget(self.time_graph_frame)
        self.equalized_graphics_view.setBackground('#19232D')
        self.equalized_graphics_view.setMouseEnabled(x=True, y=True) 
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.equalized_graphics_view.sizePolicy().hasHeightForWidth())
        self.equalized_graphics_view.setSizePolicy(sizePolicy)
        self.equalized_graphics_view.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.equalized_graphics_view.setMouseTracking(True)
        self.equalized_graphics_view.setTabletTracking(True)
        self.equalized_graphics_view.setAcceptDrops(True)
        self.equalized_graphics_view.setAutoFillBackground(False)
        self.equalized_graphics_view.setStyleSheet("")
        self.equalized_graphics_view.setObjectName("equalized_graphics_view")
        self.horizontalLayout.addWidget(self.equalized_graphics_view)
        self.equalized_sound_btn = QtWidgets.QPushButton(self.time_graph_frame)
        self.equalized_sound_btn.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border:none;")
        self.equalized_sound_btn.setText("")
        self.equalized_sound_btn.setIcon(icon)
        self.equalized_sound_btn.setIconSize(QtCore.QSize(25, 25))
        self.equalized_sound_btn.setObjectName("equalized_sound_btn")
        self.horizontalLayout.addWidget(self.equalized_sound_btn)
        self.verticalLayout.addWidget(self.time_graph_frame)
        self.controller_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controller_frame.sizePolicy().hasHeightForWidth())
        self.controller_frame.setSizePolicy(sizePolicy)
        self.controller_frame.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.controller_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controller_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controller_frame.setObjectName("controller_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.controller_frame)
        self.horizontalLayout_2.setContentsMargins(30, 10, 80, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.show_hide_btn = QtWidgets.QPushButton(self.controller_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_hide_btn.sizePolicy().hasHeightForWidth())
        self.show_hide_btn.setSizePolicy(sizePolicy)
        self.show_hide_btn.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border:none;")
        self.show_hide_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/eye copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.show_hide_btn.setIcon(icon1)
        self.show_hide_btn.setIconSize(QtCore.QSize(30, 30))
        self.show_hide_btn.setFlat(False)
        self.show_hide_btn.setObjectName("show_hide_btn")
        self.horizontalLayout_2.addWidget(self.show_hide_btn)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.line = QtWidgets.QFrame(self.controller_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.replay_btn = QtWidgets.QPushButton(self.controller_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replay_btn.sizePolicy().hasHeightForWidth())
        self.replay_btn.setSizePolicy(sizePolicy)
        self.replay_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.replay_btn.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border:none;")
        self.replay_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/rewind copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.replay_btn.setIcon(icon2)
        self.replay_btn.setIconSize(QtCore.QSize(25, 25))
        self.replay_btn.setObjectName("replay_btn")
        self.horizontalLayout_2.addWidget(self.replay_btn)
        self.play_pause_btn = QtWidgets.QPushButton(self.controller_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_pause_btn.sizePolicy().hasHeightForWidth())
        self.play_pause_btn.setSizePolicy(sizePolicy)
        self.play_pause_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.play_pause_btn.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border:none;")
        self.play_pause_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/play copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_pause_btn.setIcon(icon3)
        self.play_pause_btn.setIconSize(QtCore.QSize(22, 22))
        self.play_pause_btn.setObjectName("play_pause_btn")
        self.horizontalLayout_2.addWidget(self.play_pause_btn)
        self.stop_btn = QtWidgets.QPushButton(self.controller_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_btn.sizePolicy().hasHeightForWidth())
        self.stop_btn.setSizePolicy(sizePolicy)
        self.stop_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_btn.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border:none;")
        self.stop_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/stop-button copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_btn.setIcon(icon4)
        self.stop_btn.setIconSize(QtCore.QSize(25, 25))
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout_2.addWidget(self.stop_btn)
        self.reset_view_btn = QtWidgets.QPushButton(self.controller_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_view_btn.sizePolicy().hasHeightForWidth())
        self.reset_view_btn.setSizePolicy(sizePolicy)
        self.reset_view_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_view_btn.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border:none;")
        self.reset_view_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/arrow-up-right-and-arrow-down-left-from-center copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset_view_btn.setIcon(icon5)
        self.reset_view_btn.setIconSize(QtCore.QSize(25, 25))
        self.reset_view_btn.setObjectName("reset_view_btn")
        self.horizontalLayout_2.addWidget(self.reset_view_btn)
        self.zoom_in_btn = QtWidgets.QPushButton(self.controller_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoom_in_btn.sizePolicy().hasHeightForWidth())
        self.zoom_in_btn.setSizePolicy(sizePolicy)
        self.zoom_in_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.zoom_in_btn.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border:none;")
        self.zoom_in_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/zoom_in.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_in_btn.setIcon(icon6)
        self.zoom_in_btn.setIconSize(QtCore.QSize(25, 25))
        self.zoom_in_btn.setObjectName("zoom_in_btn")
        self.horizontalLayout_2.addWidget(self.zoom_in_btn)
        self.zoom_out_btn = QtWidgets.QPushButton(self.controller_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoom_out_btn.sizePolicy().hasHeightForWidth())
        self.zoom_out_btn.setSizePolicy(sizePolicy)
        self.zoom_out_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.zoom_out_btn.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border:none;")
        self.zoom_out_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/zoom_out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_out_btn.setIcon(icon7)
        self.zoom_out_btn.setIconSize(QtCore.QSize(25, 25))
        self.zoom_out_btn.setObjectName("zoom_out_btn")
        self.horizontalLayout_2.addWidget(self.zoom_out_btn)
        spacerItem3 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.speedLabel = QtWidgets.QLabel(self.controller_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedLabel.sizePolicy().hasHeightForWidth())
        self.speedLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        self.speedLabel.setFont(font)
        self.speedLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.speedLabel.setObjectName("speedLabel")
        self.horizontalLayout_2.addWidget(self.speedLabel)
        self.speed_slider = QtWidgets.QSlider(self.controller_frame)
        self.speed_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.speed_slider.setObjectName("speed_slider")
        self.horizontalLayout_2.addWidget(self.speed_slider)
        self.speed_lcd = QtWidgets.QLCDNumber(self.controller_frame)
        self.speed_lcd.setObjectName("speed_lcd")
        self.horizontalLayout_2.addWidget(self.speed_lcd)
        self.horizontalLayout_2.setStretch(4, 2)
        self.horizontalLayout_2.setStretch(5, 2)
        self.horizontalLayout_2.setStretch(6, 2)
        self.horizontalLayout_2.setStretch(7, 2)
        self.horizontalLayout_2.setStretch(8, 2)
        self.horizontalLayout_2.setStretch(9, 2)
        self.horizontalLayout_2.setStretch(11, 1)
        self.horizontalLayout_2.setStretch(12, 4)
        self.horizontalLayout_2.setStretch(13, 1)
        self.verticalLayout.addWidget(self.controller_frame)
        self.spectro_frame = QtWidgets.QFrame(self.centralwidget)
        self.spectro_frame.setStyleSheet("")
        self.spectro_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.spectro_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.spectro_frame.setObjectName("spectro_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.spectro_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.original_spectro_frame = QtWidgets.QFrame(self.spectro_frame)
        self.gridLayout_2 = QtWidgets.QGridLayout(self.original_spectro_frame)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.original_spectro_graphics_view = QtWidgets.QGraphicsView(self.original_spectro_frame)
        # self.original_spectro_graphics_view = pg.PlotWidget(self.original_spectro_frame)
        # self.original_spectro_graphics_view.setMouseEnabled(x=True, y=True) 
        # self.original_spectro_graphics_view.setBackground('#19232D')
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.original_spectro_graphics_view.sizePolicy().hasHeightForWidth())
        self.original_spectro_graphics_view.setSizePolicy(sizePolicy)
        self.original_spectro_graphics_view.setAutoFillBackground(False)
        self.original_spectro_graphics_view.setStyleSheet("")
        self.original_spectro_graphics_view.setObjectName("original_spectro_graphics_view")
        self.gridLayout_2.addWidget(self.original_spectro_graphics_view, 0, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.original_spectro_frame)
        self.frequency_frame = QtWidgets.QFrame(self.spectro_frame)
        self.frequency_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frequency_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frequency_frame.setObjectName("frequency_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frequency_frame)
        self.gridLayout.setContentsMargins(10, 10, 10, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        # self.frequency_graphics_view = QtWidgets.QGraphicsView(self.frequency_frame)
        self.frequency_graphics_view = pg.PlotWidget(self.frequency_frame)
        self.frequency_graphics_view.setMouseEnabled(x=True, y=True) 
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frequency_graphics_view.sizePolicy().hasHeightForWidth())
        self.frequency_graphics_view.setSizePolicy(sizePolicy)
        self.frequency_graphics_view.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frequency_graphics_view.setMouseTracking(True)
        self.frequency_graphics_view.setTabletTracking(True)
        self.frequency_graphics_view.setAcceptDrops(True)
        self.frequency_graphics_view.setAutoFillBackground(False)
        self.frequency_graphics_view.setStyleSheet("")
        self.frequency_graphics_view.setObjectName("frequency_graphics_view")
        self.gridLayout.addWidget(self.frequency_graphics_view, 0, 0, 1, 1)
        self.frequency_graphics_view.setBackground('#19232D')
        self.horizontalLayout_3.addWidget(self.frequency_frame)
        self.equalized_spectro_frame = QtWidgets.QFrame(self.spectro_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.equalized_spectro_frame.sizePolicy().hasHeightForWidth())
        self.equalized_spectro_frame.setSizePolicy(sizePolicy)
        self.equalized_spectro_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.equalized_spectro_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.equalized_spectro_frame.setObjectName("equalized_spectro_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.equalized_spectro_frame)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.equalized_spectro_graphics_view = QtWidgets.QGraphicsView(self.equalized_spectro_frame)
        # self.equalized_spectro_graphics_view = pg.PlotWidget(self.spectro_frame)
        # self.equalized_spectro_graphics_view.setMouseEnabled(x=True, y=True) 
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.equalized_spectro_graphics_view.sizePolicy().hasHeightForWidth())
        self.equalized_spectro_graphics_view.setSizePolicy(sizePolicy)
        self.equalized_spectro_graphics_view.setAutoFillBackground(False)
        self.equalized_spectro_graphics_view.setStyleSheet("")
        self.equalized_spectro_graphics_view.setObjectName("equalized_spectro_graphics_view")
        # self.equalized_spectro_graphics_view.setBackground('#19232D')
        self.gridLayout_3.addWidget(self.equalized_spectro_graphics_view, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.equalized_spectro_frame)
        self.verticalLayout.addWidget(self.spectro_frame)
        self.sliders_frame = QtWidgets.QFrame(self.centralwidget)
        self.sliders_frame.setStyleSheet("")
        self.sliders_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sliders_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sliders_frame.setObjectName("sliders_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.sliders_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.animals_sliders_frame = QtWidgets.QFrame(self.sliders_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animals_sliders_frame.sizePolicy().hasHeightForWidth())
        self.animals_sliders_frame.setSizePolicy(sizePolicy)
        self.animals_sliders_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.animals_sliders_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.animals_sliders_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.animals_sliders_frame.setObjectName("animals_sliders_frame")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.animals_sliders_frame)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(14)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.elephant_slider = QtWidgets.QSlider(self.animals_sliders_frame)
        self.elephant_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.elephant_slider.setMinimum(-10)
        self.elephant_slider.setMaximum(10)
        self.elephant_slider.setSingleStep(10)
        self.elephant_slider.setPageStep(10)
        self.elephant_slider.setProperty("value", 0)
        self.elephant_slider.setSliderPosition(0)
        self.elephant_slider.setOrientation(QtCore.Qt.Vertical)
        self.elephant_slider.setObjectName("elephant_slider")
        self.horizontalLayout_14.addWidget(self.elephant_slider)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.pushButton = QtWidgets.QPushButton(self.animals_sliders_frame)
        self.pushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/elephant.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon8)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setCheckable(False)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout_15.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(14)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.dolphin_slider = QtWidgets.QSlider(self.animals_sliders_frame)
        self.dolphin_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dolphin_slider.setMinimum(-10)
        self.dolphin_slider.setMaximum(10)
        self.dolphin_slider.setSingleStep(10)
        self.dolphin_slider.setPageStep(10)
        self.dolphin_slider.setProperty("value", 0)
        self.dolphin_slider.setSliderPosition(0)
        self.dolphin_slider.setOrientation(QtCore.Qt.Vertical)
        self.dolphin_slider.setObjectName("dolphin_slider")
        self.horizontalLayout_13.addWidget(self.dolphin_slider)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.pushButton_2 = QtWidgets.QPushButton(self.animals_sliders_frame)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/dolphin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon9)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayout_15.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 4)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.frog_slider = QtWidgets.QSlider(self.animals_sliders_frame)
        self.frog_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.frog_slider.setMinimum(-10)
        self.frog_slider.setMaximum(10)
        self.frog_slider.setSingleStep(10)
        self.frog_slider.setPageStep(10)
        self.frog_slider.setProperty("value", 0)
        self.frog_slider.setSliderPosition(0)
        self.frog_slider.setOrientation(QtCore.Qt.Vertical)
        self.frog_slider.setObjectName("frog_slider")
        self.horizontalLayout_12.addWidget(self.frog_slider)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.pushButton_3 = QtWidgets.QPushButton(self.animals_sliders_frame)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/frog-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon10)
        self.pushButton_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.horizontalLayout_15.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.cow_slider = QtWidgets.QSlider(self.animals_sliders_frame)
        self.cow_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.cow_slider.setMinimum(-10)
        self.cow_slider.setMaximum(10)
        self.cow_slider.setSingleStep(10)
        self.cow_slider.setPageStep(10)
        self.cow_slider.setProperty("value", 0)
        self.cow_slider.setSliderPosition(0)
        self.cow_slider.setOrientation(QtCore.Qt.Vertical)
        self.cow_slider.setObjectName("cow_slider")
        self.horizontalLayout_11.addWidget(self.cow_slider)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.pushButton_5 = QtWidgets.QPushButton(self.animals_sliders_frame)
        self.pushButton_5.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_5.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/cow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon11)
        self.pushButton_5.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_6.addWidget(self.pushButton_5)
        self.horizontalLayout_15.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(13)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.horse_slider = QtWidgets.QSlider(self.animals_sliders_frame)
        self.horse_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.horse_slider.setMinimum(-10)
        self.horse_slider.setMaximum(10)
        self.horse_slider.setSingleStep(10)
        self.horse_slider.setPageStep(10)
        self.horse_slider.setProperty("value", 0)
        self.horse_slider.setSliderPosition(0)
        self.horse_slider.setOrientation(QtCore.Qt.Vertical)
        self.horse_slider.setObjectName("horse_slider")
        self.horizontalLayout_10.addWidget(self.horse_slider)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.pushButton_6 = QtWidgets.QPushButton(self.animals_sliders_frame)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/horse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon12)
        self.pushButton_6.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_6.setCheckable(False)
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_7.addWidget(self.pushButton_6)
        self.horizontalLayout_15.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(13)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.wolf_slider = QtWidgets.QSlider(self.animals_sliders_frame)
        self.wolf_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.wolf_slider.setMinimum(-10)
        self.wolf_slider.setMaximum(10)
        self.wolf_slider.setSingleStep(10)
        self.wolf_slider.setPageStep(10)
        self.wolf_slider.setProperty("value", 0)
        self.wolf_slider.setSliderPosition(0)
        self.wolf_slider.setOrientation(QtCore.Qt.Vertical)
        self.wolf_slider.setObjectName("wolf_slider")
        self.horizontalLayout_9.addWidget(self.wolf_slider)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem15)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.pushButton_7 = QtWidgets.QPushButton(self.animals_sliders_frame)
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/wolf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon13)
        self.pushButton_7.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_7.setCheckable(False)
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_8.addWidget(self.pushButton_7)
        self.horizontalLayout_15.addLayout(self.verticalLayout_8)
        self.horizontalLayout_4.addWidget(self.animals_sliders_frame)
        self.music_sliders_frame = QtWidgets.QFrame(self.sliders_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.music_sliders_frame.sizePolicy().hasHeightForWidth())
        self.music_sliders_frame.setSizePolicy(sizePolicy)
        self.music_sliders_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.music_sliders_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.music_sliders_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.music_sliders_frame.setObjectName("music_sliders_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.music_sliders_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(12)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem16)
        self.guitar_slider = QtWidgets.QSlider(self.music_sliders_frame)
        self.guitar_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.guitar_slider.setMinimum(0)
        self.guitar_slider.setMaximum(100)
        self.guitar_slider.setSingleStep(10)
        self.guitar_slider.setPageStep(10)
        self.guitar_slider.setProperty("value", 0)
        self.guitar_slider.setSliderPosition(0)
        self.guitar_slider.setOrientation(QtCore.Qt.Vertical)
        self.guitar_slider.setObjectName("guitar_slider")
        self.horizontalLayout_7.addWidget(self.guitar_slider)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem17)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.music_sliders_frame)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/xylophone-02.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon14)
        self.pushButton_8.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_12.addWidget(self.pushButton_8)
        self.horizontalLayout_6.addLayout(self.verticalLayout_12)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(12)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem18)
        self.Violin_slider = QtWidgets.QSlider(self.music_sliders_frame)
        self.Violin_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.Violin_slider.setMinimum(0)
        self.Violin_slider.setMaximum(100)
        self.Violin_slider.setSingleStep(10)
        self.Violin_slider.setPageStep(10)
        self.Violin_slider.setProperty("value", 0)
        self.Violin_slider.setSliderPosition(0)
        self.Violin_slider.setOrientation(QtCore.Qt.Vertical)
        self.Violin_slider.setObjectName("Violin_slider")
        self.horizontalLayout_16.addWidget(self.Violin_slider)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem19)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        self.pushButton_9 = QtWidgets.QPushButton(self.music_sliders_frame)
        self.pushButton_9.setEnabled(False)
        self.pushButton_9.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/icons/flute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon15)
        self.pushButton_9.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_11.addWidget(self.pushButton_9)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(12)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem20)
        self.drums_slider = QtWidgets.QSlider(self.music_sliders_frame)
        self.drums_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.drums_slider.setMinimum(0)
        self.drums_slider.setMaximum(100)
        self.drums_slider.setSingleStep(10)
        self.drums_slider.setPageStep(10)
        self.drums_slider.setProperty("value", 0)
        self.drums_slider.setSliderPosition(0)
        self.drums_slider.setOrientation(QtCore.Qt.Vertical)
        self.drums_slider.setObjectName("drums_slider")
        self.horizontalLayout_19.addWidget(self.drums_slider)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem21)
        self.verticalLayout_16.addLayout(self.horizontalLayout_19)
        self.pushButton_12 = QtWidgets.QPushButton(self.music_sliders_frame)
        self.pushButton_12.setEnabled(False)
        self.pushButton_12.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/icons/chimes-01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon16)
        self.pushButton_12.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_12.setFlat(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_16.addWidget(self.pushButton_12)
        self.horizontalLayout_6.addLayout(self.verticalLayout_16)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem22)
        self.Saxophone_slider = QtWidgets.QSlider(self.music_sliders_frame)
        self.Saxophone_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.Saxophone_slider.setMinimum(0)
        self.Saxophone_slider.setMaximum(100)
        self.Saxophone_slider.setSingleStep(10)
        self.Saxophone_slider.setPageStep(10)
        self.Saxophone_slider.setProperty("value", 0)
        self.Saxophone_slider.setSliderPosition(0)
        self.Saxophone_slider.setOrientation(QtCore.Qt.Vertical)
        self.Saxophone_slider.setObjectName("Saxophone_slider")
        self.horizontalLayout_18.addWidget(self.Saxophone_slider)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem23)
        self.verticalLayout_9.addLayout(self.horizontalLayout_18)
        self.pushButton_10 = QtWidgets.QPushButton(self.music_sliders_frame)
        self.pushButton_10.setEnabled(False)
        self.pushButton_10.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/icons/piano.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon17)
        self.pushButton_10.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_9.addWidget(self.pushButton_10)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.horizontalLayout_4.addWidget(self.music_sliders_frame)
        self.ecg_sliders_frame = QtWidgets.QFrame(self.sliders_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ecg_sliders_frame.sizePolicy().hasHeightForWidth())
        self.ecg_sliders_frame.setSizePolicy(sizePolicy)
        self.ecg_sliders_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ecg_sliders_frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ecg_sliders_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ecg_sliders_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ecg_sliders_frame.setObjectName("ecg_sliders_frame")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.ecg_sliders_frame)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem24)
        self.vf_arrhythmia_slider = QtWidgets.QSlider(self.ecg_sliders_frame)
        self.vf_arrhythmia_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.vf_arrhythmia_slider.setMinimum(0)
        self.vf_arrhythmia_slider.setMaximum(130)
        self.vf_arrhythmia_slider.setSingleStep(1)
        self.vf_arrhythmia_slider.setPageStep(10)
        self.vf_arrhythmia_slider.setProperty("value", 0)
        self.vf_arrhythmia_slider.setSliderPosition(0)
        self.vf_arrhythmia_slider.setTracking(True)
        self.vf_arrhythmia_slider.setOrientation(QtCore.Qt.Vertical)
        self.vf_arrhythmia_slider.setInvertedAppearance(False)
        self.vf_arrhythmia_slider.setObjectName("p_wave_arrhythmia_slider")
        self.horizontalLayout_8.addWidget(self.vf_arrhythmia_slider)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem25)
        self.verticalLayout_13.addLayout(self.horizontalLayout_8)
        self.label_2 = QtWidgets.QLabel(self.ecg_sliders_frame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_13.addWidget(self.label_2)
        self.horizontalLayout_33.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem26)
        self.mi_arrhythmia_slider = QtWidgets.QSlider(self.ecg_sliders_frame)
        self.mi_arrhythmia_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.mi_arrhythmia_slider.setMinimum(0)
        self.mi_arrhythmia_slider.setMaximum(130)
        self.mi_arrhythmia_slider.setSingleStep(1)
        self.mi_arrhythmia_slider.setPageStep(10)
        self.mi_arrhythmia_slider.setProperty("value", 0)
        self.mi_arrhythmia_slider.setOrientation(QtCore.Qt.Vertical)
        self.mi_arrhythmia_slider.setInvertedAppearance(False)
        self.mi_arrhythmia_slider.setObjectName("sv_arrhythmia_slider")
        self.horizontalLayout_22.addWidget(self.mi_arrhythmia_slider)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem27)
        self.verticalLayout_14.addLayout(self.horizontalLayout_22)
        self.label_3 = QtWidgets.QLabel(self.ecg_sliders_frame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_14.addWidget(self.label_3)
        self.horizontalLayout_33.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem28)
        self.sr_arrhythmia_slider = QtWidgets.QSlider(self.ecg_sliders_frame)
        self.sr_arrhythmia_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.sr_arrhythmia_slider.setMinimum(0)
        self.sr_arrhythmia_slider.setMaximum(130)
        self.sr_arrhythmia_slider.setSingleStep(1)
        self.sr_arrhythmia_slider.setPageStep(10)
        self.sr_arrhythmia_slider.setProperty("value", 0)
        self.sr_arrhythmia_slider.setOrientation(QtCore.Qt.Vertical)
        self.sr_arrhythmia_slider.setInvertedAppearance(False)
        self.sr_arrhythmia_slider.setObjectName("nr_arrhythmia_slider")
        self.horizontalLayout_32.addWidget(self.sr_arrhythmia_slider)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem29)
        self.verticalLayout_15.addLayout(self.horizontalLayout_32)
        self.label_4 = QtWidgets.QLabel(self.ecg_sliders_frame)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_15.addWidget(self.label_4)
        self.horizontalLayout_33.addLayout(self.verticalLayout_15)
        self.horizontalLayout_4.addWidget(self.ecg_sliders_frame)
        self.uniform_sliders_frame = QtWidgets.QFrame(self.sliders_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uniform_sliders_frame.sizePolicy().hasHeightForWidth())
        self.uniform_sliders_frame.setSizePolicy(sizePolicy)
        self.uniform_sliders_frame.setMaximumSize(QtCore.QSize(16777215, 148))
        self.uniform_sliders_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.uniform_sliders_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.uniform_sliders_frame.setObjectName("uniform_sliders_frame")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.uniform_sliders_frame)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem30 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem30)
        self.uniform_slider_1 = QtWidgets.QSlider(self.uniform_sliders_frame)
        self.uniform_slider_1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.uniform_slider_1.setMinimum(0)
        self.uniform_slider_1.setMaximum(100)
        self.uniform_slider_1.setSingleStep(10)
        self.uniform_slider_1.setPageStep(10)
        self.uniform_slider_1.setProperty("value", 0)
        self.uniform_slider_1.setOrientation(QtCore.Qt.Vertical)
        self.uniform_slider_1.setObjectName("uniform_slider_1")
        self.horizontalLayout_27.addWidget(self.uniform_slider_1)
        spacerItem31 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem31)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem32 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem32)
        self.uniform_slider_2 = QtWidgets.QSlider(self.uniform_sliders_frame)
        self.uniform_slider_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.uniform_slider_2.setMinimum(0)
        self.uniform_slider_2.setMaximum(100)
        self.uniform_slider_2.setSingleStep(10)
        self.uniform_slider_2.setPageStep(10)
        self.uniform_slider_2.setProperty("value", 0)
        self.uniform_slider_2.setOrientation(QtCore.Qt.Vertical)
        self.uniform_slider_2.setObjectName("uniform_slider_2")
        self.horizontalLayout_25.addWidget(self.uniform_slider_2)
        spacerItem33 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem33)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem34 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem34)
        self.uniform_slider_3 = QtWidgets.QSlider(self.uniform_sliders_frame)
        self.uniform_slider_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.uniform_slider_3.setMinimum(0)
        self.uniform_slider_3.setMaximum(100)
        self.uniform_slider_3.setSingleStep(10)
        self.uniform_slider_3.setPageStep(10)
        self.uniform_slider_3.setProperty("value", 0)
        self.uniform_slider_3.setOrientation(QtCore.Qt.Vertical)
        self.uniform_slider_3.setObjectName("uniform_slider_3")
        self.horizontalLayout_23.addWidget(self.uniform_slider_3)
        spacerItem35 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem35)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem36 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem36)
        self.uniform_slider_4 = QtWidgets.QSlider(self.uniform_sliders_frame)
        self.uniform_slider_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.uniform_slider_4.setMinimum(0)
        self.uniform_slider_4.setMaximum(100)
        self.uniform_slider_4.setSingleStep(10)
        self.uniform_slider_4.setPageStep(10)
        self.uniform_slider_4.setProperty("value", 0)
        self.uniform_slider_4.setOrientation(QtCore.Qt.Vertical)
        self.uniform_slider_4.setObjectName("uniform_slider_4")
        self.horizontalLayout_28.addWidget(self.uniform_slider_4)
        spacerItem37 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem37)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem38 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem38)
        self.uniform_slider_5 = QtWidgets.QSlider(self.uniform_sliders_frame)
        self.uniform_slider_5.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.uniform_slider_5.setMinimum(0)
        self.uniform_slider_5.setMaximum(100)
        self.uniform_slider_5.setSingleStep(10)
        self.uniform_slider_5.setPageStep(10)
        self.uniform_slider_5.setProperty("value", 0)
        self.uniform_slider_5.setOrientation(QtCore.Qt.Vertical)
        self.uniform_slider_5.setObjectName("uniform_slider_5")
        self.horizontalLayout_26.addWidget(self.uniform_slider_5)
        spacerItem39 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem39)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem40 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem40)
        self.uniform_slider_6 = QtWidgets.QSlider(self.uniform_sliders_frame)
        self.uniform_slider_6.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.uniform_slider_6.setMinimum(0)
        self.uniform_slider_6.setMaximum(100)
        self.uniform_slider_6.setSingleStep(10)
        self.uniform_slider_6.setPageStep(10)
        self.uniform_slider_6.setProperty("value", 0)
        self.uniform_slider_6.setOrientation(QtCore.Qt.Vertical)
        self.uniform_slider_6.setObjectName("uniform_slider_6")
        self.horizontalLayout_24.addWidget(self.uniform_slider_6)
        spacerItem41 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem41)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        spacerItem42 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem42)
        self.uniform_slider_7 = QtWidgets.QSlider(self.uniform_sliders_frame)
        self.uniform_slider_7.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.uniform_slider_7.setMinimum(0)
        self.uniform_slider_7.setMaximum(100)
        self.uniform_slider_7.setSingleStep(10)
        self.uniform_slider_7.setPageStep(10)
        self.uniform_slider_7.setProperty("value", 0)
        self.uniform_slider_7.setOrientation(QtCore.Qt.Vertical)
        self.uniform_slider_7.setObjectName("uniform_slider_7")
        self.horizontalLayout_29.addWidget(self.uniform_slider_7)
        spacerItem43 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem43)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem44 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem44)
        self.uniform_slider_8 = QtWidgets.QSlider(self.uniform_sliders_frame)
        self.uniform_slider_8.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.uniform_slider_8.setMinimum(0)
        self.uniform_slider_8.setMaximum(100)
        self.uniform_slider_8.setSingleStep(10)
        self.uniform_slider_8.setPageStep(10)
        self.uniform_slider_8.setProperty("value", 0)
        self.uniform_slider_8.setOrientation(QtCore.Qt.Vertical)
        self.uniform_slider_8.setObjectName("uniform_slider_8")
        self.horizontalLayout_21.addWidget(self.uniform_slider_8)
        spacerItem45 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem45)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        spacerItem46 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem46)
        self.uniform_slider_9 = QtWidgets.QSlider(self.uniform_sliders_frame)
        self.uniform_slider_9.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.uniform_slider_9.setMinimum(0)
        self.uniform_slider_9.setMaximum(100)
        self.uniform_slider_9.setSingleStep(10)
        self.uniform_slider_9.setPageStep(10)
        self.uniform_slider_9.setProperty("value", 0)
        self.uniform_slider_9.setOrientation(QtCore.Qt.Vertical)
        self.uniform_slider_9.setObjectName("uniform_slider_9")
        self.horizontalLayout_30.addWidget(self.uniform_slider_9)
        spacerItem47 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem47)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem48 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem48)
        self.uniform_slider_10 = QtWidgets.QSlider(self.uniform_sliders_frame)
        self.uniform_slider_10.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.uniform_slider_10.setMinimum(0)
        self.uniform_slider_10.setMaximum(100)
        self.uniform_slider_10.setSingleStep(10)
        self.uniform_slider_10.setPageStep(10)
        self.uniform_slider_10.setProperty("value", 0)
        self.uniform_slider_10.setOrientation(QtCore.Qt.Vertical)
        self.uniform_slider_10.setObjectName("uniform_slider_10")
        self.horizontalLayout_20.addWidget(self.uniform_slider_10)
        spacerItem49 = QtWidgets.QSpacerItem(13, 184, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem49)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_4.addWidget(self.uniform_sliders_frame)
        self.verticalLayout.addWidget(self.sliders_frame)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 7)
        self.verticalLayout.setStretch(4, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        self.speed_slider.valueChanged['int'].connect(self.speed_lcd.display) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_btn.setText(_translate("MainWindow", "Open"))
        self.mode_comboBox.setItemText(0, _translate("MainWindow", "Uniform Mode"))
        self.mode_comboBox.setItemText(1, _translate("MainWindow", "Animal Mode"))
        self.mode_comboBox.setItemText(2, _translate("MainWindow", "Musical Mode"))
        self.mode_comboBox.setItemText(3, _translate("MainWindow", "ECG Mode"))
        self.replay_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Replay activate siganls</p></body></html>"))
        self.replay_btn.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.stop_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Stop activate signals</p></body></html>"))
        self.reset_view_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Back to orignial view</p></body></html>"))
        self.speedLabel.setText(_translate("MainWindow", "Speed"))
        self.label_2.setText(_translate("MainWindow", "ventricular fibrillation"))
        self.label_3.setText(_translate("MainWindow", "Premature Ventricular Contractions"))
        self.label_4.setText(_translate("MainWindow", "Brugada syndrome"))
import res_rc
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
